# Generated by Django 6.0.2 on 2026-05-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('company', 'Company'), ('lecturer', 'Lecturer')], max_length=20)),
                ('name', models.CharField(max_length=140)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('registration_number', models.CharField(max_length=80)),
                ('university', models.CharField(max_length=160)),
                ('internship_months', models.PositiveIntegerField(default=3)),
                ('photo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='internship.account')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'registration_number')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('attendance_days', models.PositiveIntegerField(default=0)),
                ('activities', models.TextField()),
                ('company_comments', models.TextField(blank=True)),
                ('lecturer_mark', models.PositiveIntegerField(blank=True, null=True)),
                ('lecturer_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='internship.studentprofile')),
            ],
            options={
                'ordering': ['student__name', 'week_number'],
                'unique_together': {('student', 'week_number')},
            },
        ),
    ]
